
server.port=9000

server.servlet.context-path=/api


# PostgreSQL connection details
spring.datasource.url=jdbc:postgresql://localhost:5432/Kanban
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
